// Generated from xrpld include/xrpl/protocol/detail/ledger_entries.macro.
pub(crate) const LEDGER_COMMON_FIELD_SPECS: &[LedgerFormatFieldSpec] = &[
    LedgerFormatFieldSpec { field_symbol: "sfLedgerIndex", style: SOEStyle::Optional },
    LedgerFormatFieldSpec { field_symbol: "sfLedgerEntryType", style: SOEStyle::Required },
    LedgerFormatFieldSpec { field_symbol: "sfFlags", style: SOEStyle::Required },
];

pub(crate) const LEDGER_FORMAT_SPECS: &[LedgerFormatSpecInit] = &[
    LedgerFormatSpecInit {
        tag_name: "ltNFTOKEN_OFFER",
        value: 0x0037,
        name: "NFTokenOffer",
        rpc_name: "nft_offer",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfNFTokenID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfNFTokenOfferNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltCHECK",
        value: 0x0043,
        name: "Check",
        rpc_name: "check",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSendMax", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfInvoiceID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfSourceTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltDID",
        value: 0x0049,
        name: "DID",
        rpc_name: "did",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDIDDocument", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltNEGATIVE_UNL",
        value: 0x004e,
        name: "NegativeUNL",
        rpc_name: "nunl",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfDisabledValidators", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfValidatorToDisable", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfValidatorToReEnable", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltNFTOKEN_PAGE",
        value: 0x0050,
        name: "NFTokenPage",
        rpc_name: "nft_page",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfPreviousPageMin", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfNextPageMin", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfNFTokens", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltSIGNER_LIST",
        value: 0x0053,
        name: "SignerList",
        rpc_name: "signer_list",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSignerQuorum", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSignerEntries", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSignerListID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltTICKET",
        value: 0x0054,
        name: "Ticket",
        rpc_name: "ticket",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfTicketSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltACCOUNT_ROOT",
        value: 0x0061,
        name: "AccountRoot",
        rpc_name: "account",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfBalance", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerCount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAccountTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfRegularKey", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfEmailHash", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfWalletLocator", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfWalletSize", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfMessageKey", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTransferRate", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDomain", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTickSize", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTicketCount", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfNFTokenMinter", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfMintedNFTokens", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfBurnedNFTokens", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfFirstNFTokenSequence", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfAMMID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltDIR_NODE",
        value: 0x0064,
        name: "DirectoryNode",
        rpc_name: "directory",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerPaysCurrency", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerPaysIssuer", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerPaysMPT", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerGetsCurrency", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerGetsIssuer", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTakerGetsMPT", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfExchangeRate", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfIndexes", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfRootIndex", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfIndexNext", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfIndexPrevious", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfNFTokenID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltAMENDMENTS",
        value: 0x0066,
        name: "Amendments",
        rpc_name: "amendments",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAmendments", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfMajorities", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltLEDGER_HASHES",
        value: 0x0068,
        name: "LedgerHashes",
        rpc_name: "hashes",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfFirstLedgerSequence", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfLastLedgerSequence", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfHashes", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltBRIDGE",
        value: 0x0069,
        name: "Bridge",
        rpc_name: "bridge",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfMinAccountCreateAmount", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainClaimID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainAccountCreateCount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainAccountClaimCount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltOFFER",
        value: 0x006f,
        name: "Offer",
        rpc_name: "offer",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfTakerPays", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfTakerGets", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfBookDirectory", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfBookNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfAdditionalBooks", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltDEPOSIT_PREAUTH",
        value: 0x0070,
        name: "DepositPreauth",
        rpc_name: "deposit_preauth",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAuthorize", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAuthorizeCredentials", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltXCHAIN_OWNED_CLAIM_ID",
        value: 0x0071,
        name: "XChainOwnedClaimID",
        rpc_name: "xchain_owned_claim_id",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainClaimID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOtherChainSource", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainClaimAttestations", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltRIPPLE_STATE",
        value: 0x0072,
        name: "RippleState",
        rpc_name: "state",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfBalance", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLowLimit", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfHighLimit", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLowNode", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfLowQualityIn", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfLowQualityOut", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfHighNode", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfHighQualityIn", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfHighQualityOut", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltFEE_SETTINGS",
        value: 0x0073,
        name: "FeeSettings",
        rpc_name: "fee",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfBaseFee", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfReferenceFeeUnits", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfReserveBase", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfReserveIncrement", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfBaseFeeDrops", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfReserveBaseDrops", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfReserveIncrementDrops", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID",
        value: 0x0074,
        name: "XChainOwnedCreateAccountClaimID",
        rpc_name: "xchain_owned_create_account_claim_id",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainAccountCreateCount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfXChainCreateAccountAttestations", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltESCROW",
        value: 0x0075,
        name: "Escrow",
        rpc_name: "escrow",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfCondition", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfCancelAfter", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfFinishAfter", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfSourceTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationNode", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfTransferRate", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfIssuerNode", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltPAYCHAN",
        value: 0x0078,
        name: "PayChannel",
        rpc_name: "payment_channel",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfBalance", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPublicKey", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSettleDelay", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfCancelAfter", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfSourceTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDestinationNode", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltAMM",
        value: 0x0079,
        name: "AMM",
        rpc_name: "amm",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfTradingFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfVoteSlots", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfAuctionSlot", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfLPTokenBalance", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltMPTOKEN_ISSUANCE",
        value: 0x007e,
        name: "MPTokenIssuance",
        rpc_name: "mpt_issuance",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfIssuer", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfTransferFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAssetScale", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfMaximumAmount", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOutstandingAmount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLockedAmount", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfMPTokenMetadata", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfMutableFlags", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfReferenceHolding", style: SOEStyle::Optional },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltMPTOKEN",
        value: 0x007f,
        name: "MPToken",
        rpc_name: "mptoken",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfMPTokenIssuanceID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfMPTAmount", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLockedAmount", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltORACLE",
        value: 0x0080,
        name: "Oracle",
        rpc_name: "oracle",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOracleDocumentID", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfProvider", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPriceDataSeries", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAssetClass", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLastUpdateTime", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltCREDENTIAL",
        value: 0x0081,
        name: "Credential",
        rpc_name: "credential",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfSubject", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfIssuer", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfCredentialType", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfIssuerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSubjectNode", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltPERMISSIONED_DOMAIN",
        value: 0x0082,
        name: "PermissionedDomain",
        rpc_name: "permissioned_domain",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAcceptedCredentials", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltDELEGATE",
        value: 0x0083,
        name: "Delegate",
        rpc_name: "delegate",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAuthorize", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPermissions", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltVAULT",
        value: 0x0084,
        name: "Vault",
        rpc_name: "vault",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional },
            LedgerFormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAssetsTotal", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfAssetsAvailable", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfAssetsMaximum", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLossUnrealized", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfShareMPTID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfWithdrawalPolicy", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfScale", style: SOEStyle::Default },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltLOAN_BROKER",
        value: 0x0088,
        name: "LoanBroker",
        rpc_name: "loan_broker",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfVaultNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLoanSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfManagementFeeRate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerCount", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfDebtTotal", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfDebtMaximum", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfCoverAvailable", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfCoverRateMinimum", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfCoverRateLiquidation", style: SOEStyle::Default },
        ],
    },
    LedgerFormatSpecInit {
        tag_name: "ltLOAN",
        value: 0x0089,
        name: "Loan",
        rpc_name: "loan",
        field_specs: &[
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousTxnLgrSeq", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfOwnerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLoanBrokerNode", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLoanSequence", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfBorrower", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfLoanOriginationFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLoanServiceFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLatePaymentFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfClosePaymentFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfOverpaymentFee", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfInterestRate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLateInterestRate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfCloseInterestRate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfOverpaymentInterestRate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfStartDate", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPaymentInterval", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfGracePeriod", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfPreviousPaymentDueDate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfNextPaymentDueDate", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfPaymentRemaining", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfPeriodicPayment", style: SOEStyle::Required },
            LedgerFormatFieldSpec { field_symbol: "sfPrincipalOutstanding", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfTotalValueOutstanding", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfManagementFeeOutstanding", style: SOEStyle::Default },
            LedgerFormatFieldSpec { field_symbol: "sfLoanScale", style: SOEStyle::Default },
        ],
    },
];
