use crate::job::JobType;
use crate::job_type_info::JobTypeInfo;
use std::collections::BTreeMap;
use std::sync::OnceLock;
use std::time::Duration;

pub const INVALID_JOB_TYPE_INFO: JobTypeInfo = JobTypeInfo::new(
    JobType::Invalid,
    "invalid",
    0,
    Duration::ZERO,
    Duration::ZERO,
);

pub const JOB_TYPE_INFOS: &[JobTypeInfo] = &[
    JobTypeInfo::new(
        JobType::Pack,
        "makeFetchPack",
        1,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::PubOldLedger,
        "publishAcqLedger",
        2,
        Duration::from_millis(10_000),
        Duration::from_millis(15_000),
    ),
    JobTypeInfo::new(
        JobType::ValidationUt,
        "untrustedValidation",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::Manifest,
        "manifest",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::TransactionL,
        "localTransaction",
        i32::MAX,
        Duration::from_millis(100),
        Duration::from_millis(500),
    ),
    JobTypeInfo::new(
        JobType::ReplayReq,
        "ledgerReplayRequest",
        10,
        Duration::from_millis(250),
        Duration::from_millis(1_000),
    ),
    JobTypeInfo::new(
        JobType::LedgerReq,
        "ledgerRequest",
        3,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::ProposalUt,
        "untrustedProposal",
        i32::MAX,
        Duration::from_millis(500),
        Duration::from_millis(1_250),
    ),
    JobTypeInfo::new(
        JobType::ReplayTask,
        "ledgerReplayTask",
        i32::MAX,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::LedgerData,
        "ledgerData",
        3,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::Client,
        "clientCommand",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientSubscribe,
        "clientSubscribe",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientFeeChange,
        "clientFeeChange",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientConsensus,
        "clientConsensus",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientAcctHist,
        "clientAccountHistory",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientRpc,
        "clientRPC",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::ClientWebsocket,
        "clientWebsocket",
        i32::MAX,
        Duration::from_millis(2_000),
        Duration::from_millis(5_000),
    ),
    JobTypeInfo::new(
        JobType::Rpc,
        "RPC",
        i32::MAX,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::UpdatePf,
        "updatePaths",
        1,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::Transaction,
        "transaction",
        i32::MAX,
        Duration::from_millis(250),
        Duration::from_millis(1_000),
    ),
    JobTypeInfo::new(
        JobType::Batch,
        "batch",
        i32::MAX,
        Duration::from_millis(250),
        Duration::from_millis(1_000),
    ),
    JobTypeInfo::new(
        JobType::Advance,
        "advanceLedger",
        i32::MAX,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::PubLedger,
        "publishNewLedger",
        i32::MAX,
        Duration::from_millis(3_000),
        Duration::from_millis(4_500),
    ),
    JobTypeInfo::new(
        JobType::TxnData,
        "fetchTxnData",
        5,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::Wal,
        "writeAhead",
        i32::MAX,
        Duration::from_millis(1_000),
        Duration::from_millis(2_500),
    ),
    JobTypeInfo::new(
        JobType::ValidationT,
        "trustedValidation",
        i32::MAX,
        Duration::from_millis(500),
        Duration::from_millis(1_500),
    ),
    JobTypeInfo::new(
        JobType::Write,
        "writeObjects",
        i32::MAX,
        Duration::from_millis(1_750),
        Duration::from_millis(2_500),
    ),
    JobTypeInfo::new(
        JobType::Accept,
        "acceptLedger",
        i32::MAX,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::ProposalT,
        "trustedProposal",
        i32::MAX,
        Duration::from_millis(100),
        Duration::from_millis(500),
    ),
    JobTypeInfo::new(JobType::Sweep, "sweep", 1, Duration::ZERO, Duration::ZERO),
    JobTypeInfo::new(
        JobType::NetopCluster,
        "clusterReport",
        1,
        Duration::from_millis(9_999),
        Duration::from_millis(9_999),
    ),
    JobTypeInfo::new(
        JobType::NetopTimer,
        "heartbeat",
        1,
        Duration::from_millis(999),
        Duration::from_millis(999),
    ),
    JobTypeInfo::new(
        JobType::Admin,
        "administration",
        i32::MAX,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::MissingTxn,
        "handleHaveTransactions",
        1_200,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::RequestedTxn,
        "doTransactions",
        1_200,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::Peer,
        "peerCommand",
        0,
        Duration::from_millis(200),
        Duration::from_millis(2_500),
    ),
    JobTypeInfo::new(
        JobType::Disk,
        "diskAccess",
        0,
        Duration::from_millis(500),
        Duration::from_millis(1_000),
    ),
    JobTypeInfo::new(
        JobType::TxnProc,
        "processTransaction",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::ObSetup,
        "orderBookSetup",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::PathFind,
        "pathFind",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::HoRead,
        "nodeRead",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::HoWrite,
        "nodeWrite",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::Generic,
        "generic",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::NsSyncRead,
        "SyncReadNode",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::NsAsyncRead,
        "AsyncReadNode",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
    JobTypeInfo::new(
        JobType::NsWrite,
        "WriteNode",
        0,
        Duration::ZERO,
        Duration::ZERO,
    ),
];

pub struct JobTypes;

impl JobTypes {
    pub fn instance() -> &'static Self {
        static INSTANCE: JobTypes = JobTypes;
        &INSTANCE
    }

    pub fn all(&self) -> &'static [JobTypeInfo] {
        JOB_TYPE_INFOS
    }

    pub fn get(&self, job_type: JobType) -> JobTypeInfo {
        self.map()
            .get(&job_type)
            .copied()
            .unwrap_or(INVALID_JOB_TYPE_INFO)
    }

    pub const fn get_invalid(&self) -> JobTypeInfo {
        INVALID_JOB_TYPE_INFO
    }

    pub fn size(&self) -> usize {
        JOB_TYPE_INFOS.len()
    }

    pub fn name(job_type: JobType) -> &'static str {
        Self::instance().get(job_type).name()
    }

    pub fn iter(&self) -> impl Iterator<Item = JobTypeInfo> + '_ {
        JOB_TYPE_INFOS.iter().copied()
    }

    fn map(&self) -> &'static BTreeMap<JobType, JobTypeInfo> {
        static MAP: OnceLock<BTreeMap<JobType, JobTypeInfo>> = OnceLock::new();
        MAP.get_or_init(|| {
            JOB_TYPE_INFOS
                .iter()
                .map(|info| (info.job_type(), *info))
                .collect()
        })
    }
}
