services:
  quaxar-testnet:
    build: .
    container_name: quaxar-testnet
    restart: "no"
    ports:
      - "127.0.0.1:5005:5005"
      - "127.0.0.1:6006:6006"
      - "51235:51235"
    volumes:
      - quaxar-testnet-data:/var/lib/quaxar
      - ${QUAXAR_TESTNET_CONFIG_FILE:-./quaxar-testnet.cfg}:/etc/quaxar/quaxar.cfg:ro
    deploy:
      resources:
        limits:
          memory: 8G
    environment:
      - RUST_LOG=info,consensus=debug,inbound_ledger=debug,bootstrap=debug,overlay=info,app=info

volumes:
  quaxar-testnet-data:
