[package]
name = "rdb"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "rdb"
path = "src/lib.rs"

[dependencies]
protocol = { path = "../../xrpl/protocol" }
basics = { path = "../../xrpl/basics" }
rusqlite = { version = "0.31", features = ["bundled"] }
