[package]
name = "xrpl_core"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
name = "xrpl_core"
path = "src/lib.rs"

[dependencies]
basics = { path = "../basics" }
generator = "0.8"
protocol = { path = "../protocol" }
serde_json = "1"
quaxar-core = { path = "../../xrpld/core" }

[dev-dependencies]
tempfile = "3"
