// Generated from xrpld include/xrpl/protocol/detail/transactions.macro.
pub(crate) const TX_COMMON_FIELD_SPECS: &[FormatFieldSpec] = &[
    FormatFieldSpec { field_symbol: "sfTransactionType", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfFlags", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfSourceTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfAccount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfPreviousTxnID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfLastLedgerSequence", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfAccountTxnID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfFee", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfOperationLimit", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfMemos", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfSigningPubKey", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfTicketSequence", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfTxnSignature", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfSigners", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfNetworkID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
    FormatFieldSpec { field_symbol: "sfDelegate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
];

pub(crate) const TX_FORMAT_SPECS: &[TxFormatSpecInit] = &[
    TxFormatSpecInit {
        tag_name: "ttPAYMENT",
        value: 0,
        name: "Payment",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "createAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfSendMax", style: SOEStyle::Optional, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfPaths", style: SOEStyle::Default, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfInvoiceID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDeliverMin", style: SOEStyle::Optional, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfCredentialIDs", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttESCROW_CREATE",
        value: 1,
        name: "EscrowCreate",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfCondition", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCancelAfter", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfFinishAfter", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttESCROW_FINISH",
        value: 2,
        name: "EscrowFinish",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOfferSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfFulfillment", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCondition", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialIDs", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttACCOUNT_SET",
        value: 3,
        name: "AccountSet",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfEmailHash", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfWalletLocator", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfWalletSize", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMessageKey", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomain", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTransferRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSetFlag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfClearFlag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTickSize", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfNFTokenMinter", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttESCROW_CANCEL",
        value: 4,
        name: "EscrowCancel",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOfferSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttREGULAR_KEY_SET",
        value: 5,
        name: "SetRegularKey",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfRegularKey", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttOFFER_CREATE",
        value: 7,
        name: "OfferCreate",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfTakerPays", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTakerGets", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOfferSequence", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttOFFER_CANCEL",
        value: 8,
        name: "OfferCancel",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfOfferSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttTICKET_CREATE",
        value: 10,
        name: "TicketCreate",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfTicketCount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttSIGNER_LIST_SET",
        value: 12,
        name: "SignerListSet",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfSignerQuorum", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignerEntries", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttPAYCHAN_CREATE",
        value: 13,
        name: "PaymentChannelCreate",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSettleDelay", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPublicKey", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCancelAfter", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttPAYCHAN_FUND",
        value: 14,
        name: "PaymentChannelFund",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfChannel", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttPAYCHAN_CLAIM",
        value: 15,
        name: "PaymentChannelClaim",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfChannel", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBalance", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignature", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPublicKey", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialIDs", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCHECK_CREATE",
        value: 16,
        name: "CheckCreate",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSendMax", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfInvoiceID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCHECK_CASH",
        value: 17,
        name: "CheckCash",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfCheckID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDeliverMin", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCHECK_CANCEL",
        value: 18,
        name: "CheckCancel",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfCheckID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttDEPOSIT_PREAUTH",
        value: 19,
        name: "DepositPreauth",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAuthorize", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfUnauthorize", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAuthorizeCredentials", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfUnauthorizeCredentials", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttTRUST_SET",
        value: 20,
        name: "TrustSet",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLimitAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfQualityIn", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfQualityOut", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttACCOUNT_DELETE",
        value: 21,
        name: "AccountDelete",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "mustDeleteAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialIDs", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_MINT",
        value: 25,
        name: "NFTokenMint",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "changeNFTCounts",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenTaxon", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTransferFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfIssuer", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_BURN",
        value: 26,
        name: "NFTokenBurn",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "changeNFTCounts",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_CREATE_OFFER",
        value: 27,
        name: "NFTokenCreateOffer",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_CANCEL_OFFER",
        value: 28,
        name: "NFTokenCancelOffer",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenOffers", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_ACCEPT_OFFER",
        value: 29,
        name: "NFTokenAcceptOffer",
        delegable: "Delegation::delegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenBuyOffer", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfNFTokenSellOffer", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfNFTokenBrokerFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCLAWBACK",
        value: 30,
        name: "Clawback",
        delegable: "Delegation::delegable",
        amendment: "featureClawback",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfHolder", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_CLAWBACK",
        value: 31,
        name: "AMMClawback",
        delegable: "Delegation::delegable",
        amendment: "featureAMMClawback",
        privileges: "mayDeleteAcct | overrideFreeze",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfHolder", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_CREATE",
        value: 35,
        name: "AMMCreate",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "createPseudoAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTradingFee", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_DEPOSIT",
        value: 36,
        name: "AMMDeposit",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount2", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfEPrice", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLPTokenOut", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTradingFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_WITHDRAW",
        value: 37,
        name: "AMMWithdraw",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "mayDeleteAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount2", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfEPrice", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLPTokenIn", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_VOTE",
        value: 38,
        name: "AMMVote",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTradingFee", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_BID",
        value: 39,
        name: "AMMBid",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBidMin", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBidMax", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAuthAccounts", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMM_DELETE",
        value: 40,
        name: "AMMDelete",
        delegable: "Delegation::delegable",
        amendment: "featureAMM",
        privileges: "mustDeleteAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAsset2", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_CREATE_CLAIM_ID",
        value: 41,
        name: "XChainCreateClaimID",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOtherChainSource", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_COMMIT",
        value: 42,
        name: "XChainCommit",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfXChainClaimID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOtherChainDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_CLAIM",
        value: 43,
        name: "XChainClaim",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfXChainClaimID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_ACCOUNT_CREATE_COMMIT",
        value: 44,
        name: "XChainAccountCreateCommit",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_ADD_CLAIM_ATTESTATION",
        value: 45,
        name: "XChainAddClaimAttestation",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "createAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAttestationSignerAccount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPublicKey", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignature", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOtherChainSource", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAttestationRewardAccount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfWasLockingChainSend", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfXChainClaimID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_ADD_ACCOUNT_CREATE_ATTESTATION",
        value: 46,
        name: "XChainAddAccountCreateAttestation",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "createAcct",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAttestationSignerAccount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPublicKey", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignature", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOtherChainSource", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAttestationRewardAccount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfWasLockingChainSend", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfXChainAccountCreateCount", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_MODIFY_BRIDGE",
        value: 47,
        name: "XChainModifyBridge",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMinAccountCreateAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttXCHAIN_CREATE_BRIDGE",
        value: 48,
        name: "XChainCreateBridge",
        delegable: "Delegation::delegable",
        amendment: "featureXChainBridge",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfXChainBridge", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfSignatureReward", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMinAccountCreateAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttDID_SET",
        value: 49,
        name: "DIDSet",
        delegable: "Delegation::delegable",
        amendment: "featureDID",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDIDDocument", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttDID_DELETE",
        value: 50,
        name: "DIDDelete",
        delegable: "Delegation::delegable",
        amendment: "featureDID",
        privileges: "noPriv",
        field_specs: &[
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttORACLE_SET",
        value: 51,
        name: "OracleSet",
        delegable: "Delegation::delegable",
        amendment: "featurePriceOracle",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfOracleDocumentID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfProvider", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAssetClass", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLastUpdateTime", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPriceDataSeries", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttORACLE_DELETE",
        value: 52,
        name: "OracleDelete",
        delegable: "Delegation::delegable",
        amendment: "featurePriceOracle",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfOracleDocumentID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLEDGER_STATE_FIX",
        value: 53,
        name: "LedgerStateFix",
        delegable: "Delegation::delegable",
        amendment: "fixNFTokenPageLinks",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLedgerFixType", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBookDirectory", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttMPTOKEN_ISSUANCE_CREATE",
        value: 54,
        name: "MPTokenIssuanceCreate",
        delegable: "Delegation::delegable",
        amendment: "featureMPTokensV1",
        privileges: "createMPTIssuance",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAssetScale", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTransferFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMaximumAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMPTokenMetadata", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMutableFlags", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReferenceHolding", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttMPTOKEN_ISSUANCE_DESTROY",
        value: 55,
        name: "MPTokenIssuanceDestroy",
        delegable: "Delegation::delegable",
        amendment: "featureMPTokensV1",
        privileges: "destroyMPTIssuance",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfMPTokenIssuanceID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttMPTOKEN_ISSUANCE_SET",
        value: 56,
        name: "MPTokenIssuanceSet",
        delegable: "Delegation::delegable",
        amendment: "featureMPTokensV1",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfMPTokenIssuanceID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfHolder", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMPTokenMetadata", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfTransferFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMutableFlags", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttMPTOKEN_AUTHORIZE",
        value: 57,
        name: "MPTokenAuthorize",
        delegable: "Delegation::delegable",
        amendment: "featureMPTokensV1",
        privileges: "mustAuthorizeMPT",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfMPTokenIssuanceID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfHolder", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCREDENTIAL_CREATE",
        value: 58,
        name: "CredentialCreate",
        delegable: "Delegation::delegable",
        amendment: "featureCredentials",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfSubject", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialType", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfExpiration", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCREDENTIAL_ACCEPT",
        value: 59,
        name: "CredentialAccept",
        delegable: "Delegation::delegable",
        amendment: "featureCredentials",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfIssuer", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialType", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttCREDENTIAL_DELETE",
        value: 60,
        name: "CredentialDelete",
        delegable: "Delegation::delegable",
        amendment: "featureCredentials",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfSubject", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfIssuer", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCredentialType", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttNFTOKEN_MODIFY",
        value: 61,
        name: "NFTokenModify",
        delegable: "Delegation::delegable",
        amendment: "featureDynamicNFT",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfNFTokenID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOwner", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfURI", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttPERMISSIONED_DOMAIN_SET",
        value: 62,
        name: "PermissionedDomainSet",
        delegable: "Delegation::delegable",
        amendment: "featurePermissionedDomains",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAcceptedCredentials", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttPERMISSIONED_DOMAIN_DELETE",
        value: 63,
        name: "PermissionedDomainDelete",
        delegable: "Delegation::delegable",
        amendment: "featurePermissionedDomains",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttDELEGATE_SET",
        value: 64,
        name: "DelegateSet",
        delegable: "Delegation::notDelegable",
        amendment: "featurePermissionDelegationV1_1",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAuthorize", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPermissions", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_CREATE",
        value: 65,
        name: "VaultCreate",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "createPseudoAcct | createMPTIssuance | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfAsset", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfAssetsMaximum", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfMPTokenMetadata", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfWithdrawalPolicy", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfScale", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_SET",
        value: 66,
        name: "VaultSet",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAssetsMaximum", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDomainID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_DELETE",
        value: 67,
        name: "VaultDelete",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "mustDeleteAcct | destroyMPTIssuance | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_DEPOSIT",
        value: 68,
        name: "VaultDeposit",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "mayAuthorizeMPT | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_WITHDRAW",
        value: 69,
        name: "VaultWithdraw",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "mayDeleteMPT | mayAuthorizeMPT | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttVAULT_CLAWBACK",
        value: 70,
        name: "VaultClawback",
        delegable: "Delegation::notDelegable",
        amendment: "featureSingleAssetVault",
        privileges: "mayDeleteMPT | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfHolder", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::Supported },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttBATCH",
        value: 71,
        name: "Batch",
        delegable: "Delegation::notDelegable",
        amendment: "featureBatch",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfRawTransactions", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBatchSigners", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_BROKER_SET",
        value: 74,
        name: "LoanBrokerSet",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "createPseudoAcct | mayAuthorizeMPT",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfVaultID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfManagementFeeRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDebtMaximum", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCoverRateMinimum", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCoverRateLiquidation", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_BROKER_DELETE",
        value: 75,
        name: "LoanBrokerDelete",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "mustDeleteAcct | mayAuthorizeMPT",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_BROKER_COVER_DEPOSIT",
        value: 76,
        name: "LoanBrokerCoverDeposit",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_BROKER_COVER_WITHDRAW",
        value: 77,
        name: "LoanBrokerCoverWithdraw",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "mayAuthorizeMPT",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
            FormatFieldSpec { field_symbol: "sfDestination", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfDestinationTag", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_BROKER_COVER_CLAWBACK",
        value: 78,
        name: "LoanBrokerCoverClawback",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Optional, mpt: SOETxMPTIssue::Supported },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_SET",
        value: 80,
        name: "LoanSet",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "mayAuthorizeMPT | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanBrokerID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfData", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCounterparty", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCounterpartySignature", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLoanOriginationFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLoanServiceFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLatePaymentFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfClosePaymentFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOverpaymentFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfInterestRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLateInterestRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfCloseInterestRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfOverpaymentInterestRate", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPrincipalRequested", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPaymentTotal", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfPaymentInterval", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfGracePeriod", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_DELETE",
        value: 81,
        name: "LoanDelete",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_MANAGE",
        value: 82,
        name: "LoanManage",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "mayModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttLOAN_PAY",
        value: 84,
        name: "LoanPay",
        delegable: "Delegation::notDelegable",
        amendment: "featureLendingProtocol",
        privileges: "mayAuthorizeMPT | mustModifyVault",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLoanID", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmount", style: SOEStyle::Required, mpt: SOETxMPTIssue::Supported },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttAMENDMENT",
        value: 100,
        name: "EnableAmendment",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLedgerSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfAmendment", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttFEE",
        value: 101,
        name: "SetFee",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfLedgerSequence", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBaseFee", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReferenceFeeUnits", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReserveBase", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReserveIncrement", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfBaseFeeDrops", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReserveBaseDrops", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfReserveIncrementDrops", style: SOEStyle::Optional, mpt: SOETxMPTIssue::None },
        ],
    },
    TxFormatSpecInit {
        tag_name: "ttUNL_MODIFY",
        value: 102,
        name: "UNLModify",
        delegable: "Delegation::notDelegable",
        amendment: "uint256{}",
        privileges: "noPriv",
        field_specs: &[
            FormatFieldSpec { field_symbol: "sfUNLModifyDisabling", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfLedgerSequence", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
            FormatFieldSpec { field_symbol: "sfUNLModifyValidator", style: SOEStyle::Required, mpt: SOETxMPTIssue::None },
        ],
    },
];
